async function adminCall(action,data={}){return apiRequest(action,data);}
async function initAdmin(){requireLogin(); const u=currentUser(); if(!u||String(u.role).toUpperCase()!=='ADMIN'){location.href='dashboard.html';return;} const d=await adminCall('adminDashboard'); document.querySelector('#stats').innerHTML=[['User',d.totalUser],['Order',d.totalOrder],['Pending',d.pendingOrder],['Verifikasi',d.waitingVerification],['Berhasil',d.successfulOrder],['Pendapatan',formatIDR(d.totalRevenue)]].map(x=>`<div class="card"><div class="text-sm text-slate-400">${x[0]}</div><div class="mt-2 text-2xl font-bold">${x[1]}</div></div>`).join(''); loadAdminOrders();}
async function loadAdminOrders(){const rows=await adminCall('adminOrders'); document.querySelector('#adminOrders').innerHTML=rows.map(o=>`<tr class="border-t border-white/5"><td class="p-3">${esc(o.order_id)}</td><td class="p-3">${esc(o.nama_user)}</td><td class="p-3">${esc(o.game)}</td><td class="p-3">${formatIDR(o.total_price)}</td><td class="p-3">${statusBadge(o.status)}</td><td class="p-3"><div class="flex gap-2"><button class="btn-secondary" onclick="approve('${o.order_id}')">Setujui</button><button class="btn-danger" onclick="rejectOrder('${o.order_id}')">Tolak</button></div></td></tr>`).join('');}
async function approve(id){try{await adminCall('approvePayment',{order_id:id});toast('Pembayaran disetujui.','success');loadAdminOrders();}catch(e){toast(e.message,'error');}}
async function rejectOrder(id){const note=prompt('Alasan penolakan:')||'';try{await adminCall('rejectPayment',{order_id:id,admin_note:note});toast('Pembayaran ditolak.','success');loadAdminOrders();}catch(e){toast(e.message,'error');}}
function panel(){const p=document.querySelector('#managePanel');p.classList.remove('hidden');return p;}
async function showProducts(){const p=panel();const rows=await adminCall('manageProducts',{subaction:'list'});p.innerHTML=`<div class="flex items-center justify-between"><h2 class="text-xl font-bold">Produk</h2><button class="btn-primary" onclick="newProduct()">Tambah</button></div><div class="mt-4 space-y-2">${rows.map(x=>`<div class="flex flex-col gap-2 rounded-xl bg-slate-900 p-3 md:flex-row md:items-center md:justify-between"><div><b>${esc(x.game)} • ${Number(x.coin).toLocaleString('id-ID')}</b><div class="text-sm text-slate-400">${formatIDR(x.price)} • ${esc(x.status)}</div></div><div class="flex gap-2"><button class="btn-secondary" onclick="editProduct('${x.product_id}',${JSON.stringify(x).replaceAll('"','&quot;')})">Edit</button><button class="btn-danger" onclick="deleteProduct('${x.product_id}')">Hapus</button></div></div>`).join('')}</div>`;}
function newProduct(){const p=panel();p.innerHTML=`<h2 class="text-xl font-bold">Tambah Produk</h2><div class="mt-4 grid gap-3 md:grid-cols-2"><input id="pg" placeholder="Game, contoh BUSSID"><input id="pc" type="number" placeholder="Koin"><input id="pp" type="number" placeholder="Harga"><select id="ps"><option>ACTIVE</option><option>INACTIVE</option></select></div><button class="btn-primary mt-4" onclick="saveProduct()">Simpan</button>`;}
async function saveProduct(id=''){try{await adminCall('manageProducts',{subaction:id?'update':'create',product_id:id,game:document.querySelector('#pg').value,coin:document.querySelector('#pc').value,price:document.querySelector('#pp').value,status:document.querySelector('#ps').value});toast('Produk tersimpan.','success');showProducts();}catch(e){toast(e.message,'error')}}
function editProduct(id,x){const p=panel();p.innerHTML=`<h2 class="text-xl font-bold">Edit Produk</h2><div class="mt-4 grid gap-3 md:grid-cols-2"><input id="pg" value="${esc(x.game)}"><input id="pc" type="number" value="${x.coin}"><input id="pp" type="number" value="${x.price}"><select id="ps"><option ${x.status==='ACTIVE'?'selected':''}>ACTIVE</option><option ${x.status==='INACTIVE'?'selected':''}>INACTIVE</option></select></div><button class="btn-primary mt-4" onclick="saveProduct('${id}')">Simpan</button>`;}
async function deleteProduct(id){if(!confirm('Hapus produk?'))return;try{await adminCall('manageProducts',{subaction:'delete',product_id:id});toast('Produk dihapus.','success');showProducts()}catch(e){toast(e.message,'error')}}
async function showPromos(){const p=panel(),rows=await adminCall('managePromos',{subaction:'list'});p.innerHTML=`<div class="flex items-center justify-between"><h2 class="text-xl font-bold">Promo</h2><button class="btn-primary" onclick="newPromo()">Tambah</button></div><div class="mt-4 space-y-2">${rows.map(x=>`<div class="rounded-xl bg-slate-900 p-3"><b>${esc(x.promo_code)} — ${esc(x.promo_name)}</b><div class="text-sm text-slate-400">${esc(x.discount_type)} ${x.discount_value} • ${esc(x.status)} • dipakai ${x.used_count||0}x</div></div>`).join('')}</div>`;}
function newPromo(){const p=panel();p.innerHTML=`<h2 class="text-xl font-bold">Tambah Promo</h2><div class="mt-4 grid gap-3 md:grid-cols-2"><input id="promo_code" placeholder="PROMO10"><input id="promo_name" placeholder="Nama promo"><textarea id="promo_desc" class="md:col-span-2" placeholder="Deskripsi"></textarea><select id="promo_type"><option>PERCENTAGE</option><option>FIXED</option></select><input id="promo_value" type="number" placeholder="Nilai diskon"><input id="promo_min" type="number" placeholder="Minimal pembelian"><input id="promo_max" type="number" placeholder="Maksimal diskon"><input id="promo_limit" type="number" placeholder="Usage limit (0 = unlimited)"><select id="promo_status"><option>ACTIVE</option><option>INACTIVE</option></select></div><button class="btn-primary mt-4" onclick="savePromo()">Simpan</button>`;}
async function savePromo(){try{await adminCall('managePromos',{subaction:'create',promo_code:document.querySelector('#promo_code').value,promo_name:document.querySelector('#promo_name').value,description:document.querySelector('#promo_desc').value,discount_type:document.querySelector('#promo_type').value,discount_value:document.querySelector('#promo_value').value,minimum_purchase:document.querySelector('#promo_min').value,maximum_discount:document.querySelector('#promo_max').value,usage_limit:document.querySelector('#promo_limit').value,status:document.querySelector('#promo_status').value});toast('Promo tersimpan.','success');showPromos()}catch(e){toast(e.message,'error')}}
async function showPayments(){const p=panel(),rows=await adminCall('managePayments',{subaction:'list'});p.innerHTML=`<div class="flex items-center justify-between"><h2 class="text-xl font-bold">Metode Pembayaran</h2><button class="btn-primary" onclick="newPayment()">Tambah</button></div><div class="mt-4 space-y-2">${rows.map(x=>`<div class="rounded-xl bg-slate-900 p-3"><b>${esc(x.category)} — ${esc(x.name)}</b><div class="text-sm text-slate-400">${esc(x.account_number||'-')} • ${esc(x.status)}</div></div>`).join('')}</div>`;}
function newPayment(){const p=panel();p.innerHTML=`<h2 class="text-xl font-bold">Tambah Pembayaran</h2><div class="mt-4 grid gap-3"><select id="pay_cat"><option>QRIS</option><option>BANK</option><option>EWALLET</option></select><input id="pay_name" placeholder="Nama metode, contoh QRIS / BCA / DANA"><input id="pay_no" placeholder="Nomor rekening / nomor e-wallet"><input id="pay_owner" placeholder="Nama pemilik"><input id="pay_img" placeholder="URL gambar QRIS (opsional)"><textarea id="pay_inst" placeholder="Instruksi pembayaran"></textarea><select id="pay_status"><option>ACTIVE</option><option>INACTIVE</option></select></div><button class="btn-primary mt-4" onclick="savePayment()">Simpan</button>`;}
async function savePayment(){try{await adminCall('managePayments',{subaction:'create',category:document.querySelector('#pay_cat').value,name:document.querySelector('#pay_name').value,account_number:document.querySelector('#pay_no').value,account_name:document.querySelector('#pay_owner').value,image_url:document.querySelector('#pay_img').value,instructions:document.querySelector('#pay_inst').value,status:document.querySelector('#pay_status').value});toast('Metode pembayaran tersimpan.','success');showPayments()}catch(e){toast(e.message,'error')}}
